---
title: "SVG Selection in Human and Mouse Data"
author: "Emily Ekstrum"
date: "1/8/26"
output:
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
    theme: "cosmo"
    df_print: paged
    
params:
  mouse_rds_path: "/Users/emilyekstrum/repos/zhangLab_Rotation/data/processed/mousebrain_seurat.rds"
  human_rds_path: "/Users/emilyekstrum/repos/zhangLab_Rotation/data/processed/humanbrain_seurat.rds"
  seed: 123
---

# file setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 5
)
set.seed(params$seed)
```

# SVG Selection in Mouse Brain Spatial Transcriptomics Data

> **Input**: `r params$mouse_rds_path`

# load in packages

```{r packages}
pkgs <- c(
  "Seurat",
  "Matrix",
  "ggplot2",
  "dplyr",
  "tibble",
  "patchwork",
  "Rfast2",
  "STew",
  "BiocManager"
)

to_install <- pkgs[!vapply(pkgs, requireNamespace, logical(1), quietly = TRUE)]
if (length(to_install) > 0) {
  install.packages(to_install, repos = "https://cloud.r-project.org")
}

# Load
lapply(pkgs, library, character.only = TRUE)
```

# load in mouse data
```{r load-mouse-data}
mouse_seurat <- readRDS(params$mouse_rds_path)
mouse_seurat
```

# identify SVGs using Seurat
```{r find-mouse-svgs}
# coords (cells x 2)
spatial_loc <- as.matrix(mouse_seurat@meta.data[colnames(mouse_seurat), c("imagecol","imagerow"), drop=FALSE])
storage.mode(spatial_loc) <- "numeric"
colnames(spatial_loc) <- c("x","y")

# SCT expression (genes x cells - pearson residuals)
DefaultAssay(mouse_seurat) <- "SCT"
expr_sct <- GetAssayData(mouse_seurat, assay = "SCT", layer = "scale.data")

# can only use HVGs to speed up
#hvg <- as.character(VariableFeatures(mouse_seurat))
#expr_sct <- expr_sct[hvg, , drop = FALSE]

# run Moran's I SVG
svg_df <- FindSpatiallyVariableFeatures(
  object = expr_sct,
  spatial.location = spatial_loc,
  selection.method = "moransi"
)

# svg_df is the data.frame returned by FindSpatiallyVariableFeatures()
# inspect output
names(svg_df)
str(svg_df)

# get score columne
score_col <- intersect(
  c("moransi", "MoranI", "moran.i", "I", "observed", "statistic"),
  names(svg_df)
)[1]

if (is.na(score_col)) {
  stop("Couldn't find a Moran's I score column. Check names(svg_df).")
}

# score -> numeric vector (handles list/df columns)
score <- svg_df[[score_col]]
if (is.data.frame(score)) score <- score[[1]]
score <- as.numeric(score)

# order genes by score (high to low)
svg_genes <- rownames(svg_df)[order(score, decreasing = TRUE)]
head(svg_genes, 20)

# store
mouse_seurat@misc$svg_sct_moransi_table <- svg_df
mouse_seurat@misc$svg_sct_moransi_genes <- svg_genes
```

```{r}
length(nrows(mouse_seurat@misc$svg_sct_moransi_table)))
```

# store SVGs in a cell by location matrix
```{r mouse-svg-matrix}
mouse_svg_matrix <- GetAssayData(mouse_seurat, assay = "SCT", layer = "data")[mouse_seurat@misc$svg_sct_moransi_genes, ]
mouse_svg_matrix[1:5, 1:5]
head(rownames(mouse_svg_matrix), 20)
```
# save mouse SVG matrix
```{r save-mouse-svg-matrix}
saveRDS(mouse_svg_matrix, file = "/Users/emilyekstrum/repos/zhangLab_Rotation/data/processed/seurat_mouse_svg_matrix.rds")
```



#------------- human data ----------------#


# load in human data
```{r load-human-data}
human_seurat <- readRDS(params$human_rds_path)
human_seurat
```


# identify SVGs using Seurat
```{r find-human-svgs}
# coords (cells x 2)
spatial_loc <- as.matrix(human_seurat@meta.data[colnames(human_seurat), c("imagecol","imagerow"), drop=FALSE])
storage.mode(spatial_loc) <- "numeric"
colnames(spatial_loc) <- c("x","y")

# SCT expression (genes x cells - pearson residuals)
DefaultAssay(human_seurat) <- "SCT"
expr_sct <- GetAssayData(human_seurat, assay = "SCT", layer = "scale.data")

# again - only restrict to HVGs
#hvg <- as.character(VariableFeatures(human_seurat))
#expr_sct <- expr_sct[hvg, , drop = FALSE]

# run Moran's I SVG
svg_df <- FindSpatiallyVariableFeatures(
  object = expr_sct,
  spatial.location = spatial_loc,
  selection.method = "moransi"
)

# svg_df is the data.frame returned by FindSpatiallyVariableFeatures(...)
# inspect output
names(svg_df)
str(svg_df)

# get score column
score_col <- intersect(
  c("moransi", "MoranI", "moran.i", "I", "observed", "statistic"),
  names(svg_df)
)[1]

if (is.na(score_col)) {
  stop("Couldn't find a Moran's I score column. Check names(svg_df).")
}

# score -> numeric vector (handles list/df columns)
score <- svg_df[[score_col]]
if (is.data.frame(score)) score <- score[[1]]
score <- as.numeric(score)

#order genes by score (high to low)
svg_genes <- rownames(svg_df)[order(score, decreasing = TRUE)]
head(svg_genes, 20)

# store
human_seurat@misc$svg_sct_moransi_table <- svg_df
human_seurat@misc$svg_sct_moransi_genes <- svg_genes
```

# store SVGs in a cell by location matrix
```{r human-svg-matrix}
human_svg_matrix <- GetAssayData(human_seurat, assay = "SCT", layer = "data")[human_seurat@misc$svg_sct_moransi_genes, ]
human_svg_matrix[1:5, 1:5]
head(rownames(human_svg_matrix), 20)
```

# save mouse SVG matrix
```{r save-human-svg-matrix}
saveRDS(human_svg_matrix, file = "/Users/emilyekstrum/repos/zhangLab_Rotation/data/processed/seurat_human_svg_matrix.rds")
```

